# 模型文件保存路径
MODELFILE_STORAGE_PATH: C:\Users\ShallowTrace\Desktop\submission\


server:
  port: 8002

spring:
  datasource:
    username: czy
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/${database.name}?createDatabaseIfNotExist=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull

    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5
    servlet:
      multipart:
        max-file-size: 500MB
        max-request-size: 500MB

  liquibase:
    change-log: classpath:liquibase/master.xml
    enabled: true # 当实际使用的数据库不支持liquibase，如 mariadb 时，将这个参数设置为false
    drop-first: false # 为 true 的话每次启动项目会删除所有数据库表

# 默认的数据库名
database:
  name: model_eval_plat

docker:
  build:
    context: ${user.dir}