# 文件上传配置

# 模型文件保存路径
model:
  upload:
    path: c:/IDEAproject/ModelEvalPlat/uploads/
# 数据库配置
server:
  port: 8002

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/modeleval?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5